sudo: false
language: csharp

notifications:
  email: false

branches:
  only:
    - master
    - develop

git:
  depth: 1

install:
  - nuget restore TS3AudioBot.sln
  - nuget install NUnit.Runners -OutputDirectory nunit

script:
  - cfg="/p:Configuration=Release /p:Platform=x86 TS3AudioBot.sln"
  - if command -v msbuild; then
      msbuild $cfg
    elif command -v xbuild; then
      xbuild $cfg
    else
      echo "No mono build tool found!"
      false
    fi
  - mono ./nunit/NUnit.ConsoleRunner.*.*.*/tools/nunit3-console.exe ./TS3ABotUnitTests/bin/Release/TS3ABotUnitTests.dll

after_script:
  - chmod u+x ts3notify.sh
  - ./ts3notify.sh
